### PR TITLE
Update plugins for v4

### PR DESCRIPTION
**Pull request by Coolguy3289**

### CODE REVIEW

**Review by fourjr — CHANGES_REQUESTED** [review]
Thanks so much for doing this. Could we standardise to `discord.utils.utcnow()` instead of `datetime.utcnow(timezone.utc)`?

**Comment by Coolguy3289** [comment]
Will do, noticed that it was a bit neater after I made the PR

**Comment by Coolguy3289** [comment]
Commit uploaded!

**Review by fourjr — APPROVED** [review]
LGTM, thanks

**Pull request merged**
